[project]
name = "video-face-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "insightface>=0.7.3",
    "onnxruntime>=1.22.1",
]
